language: python

addons:
  apt:
    packages:
      - pandoc

python:
  - "3.4"

install:
  - pip install -r requirements-dev.txt
  - python setup.py build
  - python setup.py install

script:
  - python setup.py test
  - find . -type f -name "*.py" | xargs flake8
  - python setup.py --long-description | rst2html5.py

after_success:
  - coverage run --source woudc_data_registry setup.py test
  - coverage report -m
  - python setup.py bdist_wheel
